#!/bin/bash
#
# Skript küsib vanuse ja väljastab, kas oled laps, nooruk, täiskasnanu või senjoor.
#
echo
echo "Sisesta siia enda vanus: "
read vanus
echo
if test $vanus -ge 0 -a $vanus -lt 11 # Kui vanus on 0 - 11 (11 ei ole kaasa arvatud), siis väljastab lapse.
then
	echo "Oled laps!"
elif  test $vanus -ge 11 -a $vanus -lt 18 # Kui vanus on 11 - 18 (18 ei ole kaasa arvatud), siis väljastab nooruki.
then
	echo "Oled nooruk!" 
elif test $vanus -ge 18 -a $vanus -lt 63 # Kui vanus on 18 - 63 (63 ei ole kaasa arvatud), siis väljastab täiskasvanu. 
then
	echo "Oled täiskasvanu!"
elif test $vanus -ge 63 # Kui vanus on 63 - ..., siis väljastab senjoor.
then
	echo "Oled senjoor!"
else 
	echo "Vigane vanus!" # Kui vanus ei ole sobilik arv, siis annab veateate.
fi
echo
# Skripti lõpp.
