#!/bin/bash
#
# Skript väljastab sõltuvalt kellaajast kas "Tere hommikust", "Tere päevast", "Tere õhtust" või "Head ööd!.
#
echo
echo "Sisesta kellaeg tundides: "
read aeg
if test $aeg -ge 6 -a $aeg -lt 12 # Kui kell on 6-12, siis...
then
	echo "Tere hommikust!"
elif test $aeg -ge 12 -a $aeg -lt 18 # Kui kell on 12-18, siis...
then
	echo "Tere päevast!"
elif test $aeg -ge 18 -a $aeg -lt 22 # Kui kell on 18-22, siis...
then
	echo "Tere õhtust!"
elif test $aeg -ge 22 -a $aeg -lt 24 # Kui kell on 22-24, siis...
then
	echo "Head ööd!"
elif test $aeg -ge 0 -a $aeg -lt 6 # Kui kell on 0-6, siis...
then
	echo "Head ööd!"
else 
	echo "Vigane kellaaeg!" # Veateade
fi
echo
# Skripti lõpp.
