#!/bin/bash
#

osch=0
echo "1. Unix (Sun Os)"
echo "2. Linux (Red Hat)"

echo -n "Select your os coice [1 or 2]? "
read osch

if [ $osch -eq 1 ] ; then
	echo "You Pick Up Unix (Sun Os)"
else ### nested if i.e. if within if #####
	if [ $osch -eq 2 ] ; then
		echo "You Pick Up Linux (Red Hat)"
	else
		echo "What you don't like Unix/Linux IS?"
	fi
fi

#
